name: Snapshot

on: [push]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Do dummy changes
        run: touch new_file
      - name: Commit changes
        run: git add new_file && git commit -a -m "new file"
      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.create({...context.repo, title: context.payload.commits[0]['message'], head: context.ref, base: 'master' })
