name: main

on:
  push:

jobs:
  setup:
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: macos-latest, target: ["native", "aarch64-apple-ios", "aarch64-apple-darwin"], compiler: [{ cpp: g++-11, c: gcc-11 }, { cpp: clang++, c: clang }] }
          - { os: windows-latest }
          - { os: ubuntu-latest }
    steps:
      - name: ☁️ Checkout repository
        uses: actions/checkout@v2
